### ISSUE TITLE
Add support for ATmega64

### ISSUE THREAD

**Issue by MCUdude** [vanbwodonk/optiboot128#1]
Hi! I'm planning to create an Arduino ATmega64/128 core in the future, and it would be great with optiboot support for the ATmega64 as well. It's the mega128's little brother, which is quite similar. Here's the migration document: http://www.atmel.com/images/doc2539.pdf

**Comment by vanbwodonk** [comment]
Sure, it's similar MCU with different flash. I'm looking forward to your project (MightyCore) with ATmega128/64.

**Comment by MCUdude** [comment]
Great! The ATmega64/128 have been around for about a decade now,  but there still aren't any decent Arduino cores yet. The ATmega128 cost less than a dollar at EBay or Aliexpress, and is OK to solder by hand. It shouldn't be too much work making the Arduino core run at the Atmega64/128 :-)

**Comment by MCUdude** [comment]
I actually don't have an ATmega64, but I'll be buying one as soon at the ATmega128 breakout board arrives in the mail. May I ask, what are all the files ending with a '~' ? They looks like some kind of backup files.

**Comment by vanbwodonk** [comment]
That's hidden garbage file on linux, already deleted.

**Comment by MCUdude** [comment]
Ah,  I see. I got a similar issue on my Mac. It's saving .ds_store files all over the place. I'm using a .gitignore file to remove files like that.  

Oh, I've all ready started working on the new core. It can be found here. Still waiting for the ATmega128 board to arrive though.. 
https://github.com/MCUdude/MegaCore

**Comment by MCUdude** [comment]
Hi! I've done some testing for the Optiboot bootloader for the ATmega64, and I get this error when I try to burn the bootloader:

> avrdude: erasing chip
avrdude: Using SCK period of 10 usec
avrdude: reading input file "~/Documents/Arduino/hardware/MegaCore/avr/bootloaders/optiboot/atmega64/optiboot_atmega64_1MHz.hex"
avrdude: ERROR: address 0x20000 out of range at line 40 of ~/Arduino/hardware/MegaCore/avr/bootloaders/optiboot/atmega64/optiboot_atmega64_1MHz.hex
avrdude: read from file '~/Arduino/hardware/MegaCore/avr/bootloaders/optiboot/atmega64/optiboot_atmega64_1MHz.hex' failed

avrdude done.  Thank you.

Error while burning bootloader.

When I'm using the __avr-objcopy__ command (for converting the hex file to a binary file) the binary file size is 66560 bytes big! How can this be?

**Comment by MCUdude** [comment]
I found the problem! There is a typo in the makefile. should be:

`
#Atmega64
atmega64: MCU_TARGET = atmega64
atmega64: CFLAGS += $(COMMON_OPTIONS) -DBIGBOOT $(UART_CMD)
atmega64: AVR_FREQ ?= 16000000L
atmega64: LDSECTIONS = -Wl,--section-start=.text=0xfc00 -Wl,--section-start=.version=0xfffe
atmega64: $(PROGRAM)_atmega64.hex
atmega64: $(PROGRAM)_atmega64.lst
`

**Comment by vanbwodonk** [comment]
My bad, wrong section. Thanks,
