### ISSUE TITLE
errors during compilation bootloader for at128

### ISSUE THREAD

**Issue by bartekk942** [vanbwodonk/optiboot128#2]
Hi, 
i'm writing because i'm trying to compile bootloader for at128 but I can't cause I got errors like below:

`make atmega128
avr-gcc (GCC) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

BAUD RATE CHECK: Desired: 115200, Real: 117647, UBRRL = 16, Error=-2.1%
avr-gcc -g -Wall -Os -fno-split-wide-types -mrelax -save-temps -mmcu=atmega128 -DF_CPU=16000000L  -DBAUD_RATE=115200 -DLED_START_FLASHES=3      -DBIGBOOT    -c -o optiboot.o optiboot.c
optiboot.c:302:2: warning: #warning BAUD_RATE error greater than -2% [-Wcpp]
 #warning BAUD_RATE error greater than -2%
  ^
avr-gcc -g -Wall -Os -fno-split-wide-types -mrelax -save-temps -mmcu=atmega128 -DF_CPU=16000000L  -DBAUD_RATE=115200 -DLED_START_FLASHES=3      -DBIGBOOT  -Wl,--section-start=.text=0x1fc00 -Wl,--section-start=.version=0x1fffe -Wl,--relax -nostartfiles -nostdlib -o optiboot_atmega128.elf optiboot.o -lc
optiboot.o: In function `appStart':
/home/bartekk/Pulpit/optiboot128-master/optiboot.c:852: undefined reference to `eeprom_write_byte'
/home/bartekk/Pulpit/optiboot128-master/optiboot.c:852: undefined reference to `eeprom_read_byte'
collect2: error: ld returned 1 exit status
Makefile:538: polecenia dla obiektu 'optiboot_atmega128.elf' nie powiodły się
make: *** [optiboot_atmega128.elf] Błąd 1
rm optiboot.o
`

**Comment by bartekk942** [comment]
The solution is in PR #3

**Comment by vanbwodonk** [comment]
@bartekk942 I try to compile your PR #3 , but still same error. This problem must related to new avrlib. I compile this a year ago with no error.

**Comment by vanbwodonk** [comment]
I don't know is missing typo or something just manual type and edit Makefile >> `atmega128: LIBS += -latmega128`, compile it with no error. Thanks for submit this PR. Merge now.
